version: "3.0"
services:

#################
###   BACKEND ####
#################
  philosophy-backend:
    build: ./philosophy-backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      DJANGO_BENTO_MONGO_SERVER_URL: ${DJANGO_BENTO_MONGO_SERVER_URL}
      DJANGO_BENTO_BROKER_URL: ${DJANGO_BENTO_BROKER_URL}
      DJANGO_BENTO_CELERY_BROKER_URL: ${DJANGO_BENTO_CELERY_BROKER_URL}
      DJANGO_SETTINGS_MODULE: "philosophyrest.production_settings"
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    command: /opt/app/start-server.sh

#################
###   FRONTEND ####
#################

  philosophy-frontend:
    build: ./philosophy-frontend
    expose:
      - ${REACT_APP_PORT}
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:80
    links:
      - philosophy-backend
    #command: /opt/app/start-server.sh
